package com.javatraining.exception;

public class ExceptionPr {

	public static void main(String[] args) {
		
		try {
			int a= 25/0;
			System.out.println(a);
		}catch(Exception b) {
			System.out.println("divisible by 0 "+b.getStackTrace());
		}
		finally {
			System.out.println("this is finally block");
		}
		
		
	}
}


	
	
	
	


